export const PERMISSIONS = [
  { name: 'roles:read', description: 'View roles and permissions' },
  { name: 'roles:write', description: 'Create and update roles' },
  { name: 'roles:delete', description: 'Delete roles' },
  { name: 'invitations:read', description: 'View pending invitations' },
  { name: 'invitations:create', description: 'Send invitations' },
  { name: 'invitations:delete', description: 'Revoke invitations' },
  { name: 'agents:read', description: 'View agents' },
  { name: 'agents:create', description: 'Create agents' },
  { name: 'agents:update', description: 'Update agents' },
  { name: 'agents:delete', description: 'Delete agents' },
  { name: 'accounts:read', description: 'View accounts' },
  { name: 'accounts:create', description: 'Create accounts' },
  { name: 'accounts:update', description: 'Update accounts' },
  { name: 'accounts:delete', description: 'Delete accounts' },
  { name: 'clients:read', description: 'View clients' },
  { name: 'clients:create', description: 'Create clients' },
  { name: 'clients:update', description: 'Update clients' },
  { name: 'clients:delete', description: 'Delete clients' },
  { name: 'insurers:read', description: 'View insurers' },
  { name: 'insurers:create', description: 'Create insurers' },
  { name: 'insurers:update', description: 'Update insurers' },
  { name: 'insurers:delete', description: 'Delete insurers' },
] as const;

export type PermissionName = (typeof PERMISSIONS)[number]['name'];
